version: "3.8"
services:

    www:
        build: php
        container_name: www_site2
        # ports:
        #   - "8751:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - traefik #add 1st so traefik performs better
            - site1network
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.site2_com.rule=Host(`site2.com`)"
            - "traefik.http.services.site2_com.loadbalancer.server.port=80"

networks:
    site1network:
    traefik:
        external:
            name: traefik_global